### ISSUE TITLE
0xc000007b error when running exe from windows

### ISSUE THREAD

**Issue by urgood2** [tupini07/raylib-cpp-cmake-template#4]
Hello, I followed the instructions in the wiki to produce the exe file, but it won't run. I get an error (0xc000007b). Do you know why this might happen?

**Comment by tupini07** [comment]
Hi @urgood2 ! The error code itself doesn't tell me much 🤔 can you send me a screenshot of what you're seeing? Especially any error text that you might be seeing on your terminal
